<?xml version="1.0" encoding="utf-8"?><Database Name="Core" Class="CoreDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Core.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="MyCodex.Properties.Settings" SettingsPropertyName="CoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Chapter" Member="tbl_Chapters">
    <Type Name="tbl_Chapter">
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cname" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="BID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Tomes" Member="tbl_Tomes">
    <Type Name="tbl_Tome">
      <Column Name="TID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Pages" Member="tbl_Pages">
    <Type Name="tbl_Page">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_History" Member="tbl_Histories">
    <Type Name="tbl_History">
      <Column Name="EID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="eText" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Keywords" Member="tbl_Keywords">
    <Type Name="tbl_Keyword">
      <Column Name="KWID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Word" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_notes" Member="tbl_notes">
    <Type Name="tbl_note">
      <Column Name="nid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoteText" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Requirements" Member="tbl_Requirements">
    <Type Name="tbl_Requirement">
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReqText" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Books" Member="tbl_Books">
    <Type Name="tbl_Book">
      <Column Name="BID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
</Database>